-- create clients table
CREATE TABLE IF NOT EXISTS Clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(250),
    email VARCHAR(250) UNIQUE,
    phone VARCHAR(250) UNIQUE,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP WITH TIME ZONE NULL
);